max_planning_time: 2.5
max_segment_length: 20.0
safety_distance: 0.4 #0.5
odom_topic: "/floam/pose" #"/mavros/vision_pose/pose" #"/optitrack/pose"
#/odom_topic: "/optitrack/pose"
#/odom_topic: "/mavros/local_position/pose"
#enable_replan: True
XMIN: -5 #-4 #80 #
XMAX: 17 #4 #150 #30
YMIN: -15 #-5 #-30
YMAX: 15 #40 #30
ZMIN: 0.0 #-1
ZMAX: 1.5 #10
