/max_planning_time: 2.5
/max_segment_length: 20.0
/safety_distance: 0.5 #0.5
/odom_topic: "/floam/pose" #"/mavros/vision_pose/pose" #"/optitrack/pose"
# /odom_topic: "/mavros/local_position/pose"
#enable_replan: True
XMIN: -1 #-4 #80 #
XMAX: 12 #4 #150 #30
YMIN: -4 #-5 #-30
YMAX: 4 #40 #30
ZMIN: 0 #-1
ZMAX: 5 #10
